### ISSUE TITLE
Add Windows Install Instructions (in Wiki?)

### ISSUE THREAD

**Issue by jmh530** [kaleidicassociates/lubeck#11]
There was a [question on the forum](https://forum.dlang.org/thread/hmyaequcnoymcriresga@forum.dlang.org) about how to install this on Windows. I tried to provide some help from my experiences, but it could probably be fleshed out in more detail and put in the wiki or something.

**Comment by wilzbach** [comment]
You could also do what a few other projects do and ship the dll files as a dependency, e.g.

https://github.com/dlang/dub/blob/master/dub.sdl
https://github.com/ariovistus/pyd/blob/034e680e1231f6458478997058f9a99203f1774d/dub.json

Though I'm not a huge friend of dumping binaries into a repo, but maybe a blas-windows window-only dependency could be added, s.t. the normal users and source isn't affected?
I'm not entirely sure whether platform="windows" works for dependencies, but otherwise different configurations could be used like vibe.d:vibe-core does:

https://github.com/vibe-d/vibe.d/blob/master/core/dub.sdl

**Comment by jmh530** [comment]
@wilzbach I'm all in favor of anything that makes it easier for Windows users to use mir/lubeck.

**Comment by jmh530** [comment]
You could add the above as a project for libmir. Not really sure where it
fits in as an issue since it probably could be a dependency in multiple
places and require changes across many dub.json/sdl files.

**Comment by Laeeth** [comment]
git lfs ?
https://git-lfs.github.com/

**Comment by jmh530** [comment]
@Laeeth I thought that was more for things like game assets. I wouldn't think that a blas/lapack dll would be too big for git or github

**Comment by wilzbach** [comment]
Yeah I would assume the dlls to be a few MBs. Not too bad, but good if it can be avoided from polluting the git history and Posix downloads.
Also dub doesn't support git lfs.

**Comment by 9il** [comment]
First progress
https://github.com/kaleidicassociates/lubeck#required-system-libraries
https://github.com/libmir/mir-lapack/wiki/Link-with-CBLAS-&-LAPACK
